image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - github

services:
  - docker:19.03.0-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t docker.io/snpranav/go-api-boilerplate:alpine .
    - docker build -t docker.io/snpranav/go-api-boilerplate:latest .
    - docker login --username $docker_username --password $docker_password
    - docker push docker.io/snpranav/go-api-boilerplate:alpine
    - docker push docker.io/snpranav/go-api-boilerplate:latest

sync:
  stage: github
  script:
    - git remote add github https://$github_username:$github_push_token@github.com/snpranav/go-api-boilerplate
    - git push github