image: docker:19.03.0

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build-alpine
  - build-latest
  - push
  - github

services:
  - docker:19.03.0-dind

before_script:
  - docker info

build:
  stage: build-alpine
  script:
    - docker build -t snpranav/go-api-boilerplate:alpine .

build:
  stage: build-latest
  script:
    - docker build -t snpranav/go-api-boilerplate:latest .

push:
  stage: push
  script:
    - docker login --username $(docker_username) --password $(docker_password)
    - docker push snpranav/go-api-boilerplate:alpine
    - docker push snpranav/go-api-boilerplate:latest