name: GITLAB PUSH CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Push to GitLab for CI/CD Pipeline 
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_CI_TOKEN }}@gitlab.com/${{ secrets.GITLAB_USERNAME }}/go-api-boilerplate.git
        git push gitlab master --force
